#!/usr/bin/env python3

import sys
import math
from utils import (
    quadratic_equation_sphere,
    quadratic_equation_Cylinder,
    quadratic_equation_cone,
    coordinates_Lt,
)

USAGE = """USAGE
    ./104intersection opt xp yp zp xv yv zv p

DESCRIPTION
    opt     surface option: 1 for a sphere, 2 for a cylinder, 3 for a cone
    (xp, yp, zp)   coordinates of a point by which the light ray passes through
    (xv, yv, zv)   coordinates of a vector parallel to the light ray
    p       parameter: radius of the sphere, radius of the cylinder, or
            angle formed by the cone and the Z-axis"""


def print_point(coords):
    print("({:.3f}, {:.3f}, {:.3f})".format(coords[0], coords[1], coords[2]))


def print_results(surface_label, solutions, Vx, Vy, Vz, Px, Py, Pz):
    print(surface_label)
    print("Line passing through the point ({}, {}, {}) and parallel to the vector ({}, {}, {})".format(
        format_num(Px), format_num(Py), format_num(Pz),
        format_num(Vx), format_num(Vy), format_num(Vz),
    ))

    if solutions == -1:
        print("There is an infinite number of intersection points.")
    elif solutions is None:
        print("No intersection point.")
    elif isinstance(solutions, list):
        print("2 intersection points:")
        for t in solutions:
            coords = coordinates_Lt(Vx, Vy, Vz, Px, Py, Pz, t)
            print_point(coords)
    else:
        print("1 intersection point:")
        coords = coordinates_Lt(Vx, Vy, Vz, Px, Py, Pz, solutions)
        print_point(coords)


def format_num(n):
    if n == int(n):
        return str(int(n))
    return str(n)


def main():
    if len(sys.argv) == 2 and sys.argv[1] == "-h":
        print(USAGE)
        sys.exit(0)

    if len(sys.argv) != 9:
        sys.exit(84)

    try:
        opt = int(sys.argv[1])
        Px = float(sys.argv[2])
        Py = float(sys.argv[3])
        Pz = float(sys.argv[4])
        Vx = float(sys.argv[5])
        Vy = float(sys.argv[6])
        Vz = float(sys.argv[7])
        p  = float(sys.argv[8])

        if opt == 1:
            label = "Sphere of radius {}".format(format_num(p))
            solutions = quadratic_equation_sphere(Vx, Vy, Vz, Px, Py, Pz, p)
        elif opt == 2:
            label = "Cylinder of radius {}".format(format_num(p))
            solutions = quadratic_equation_Cylinder(Vx, Vy, Vz, Px, Py, Pz, p)
        elif opt == 3:
            label = "Cone with a {} degree angle".format(format_num(p))
            angle_rad = math.radians(p)
            solutions = quadratic_equation_cone(Vx, Vy, Vz, Px, Py, Pz, angle_rad)
        else:
            sys.exit(84)

        print_results(label, solutions, Vx, Vy, Vz, Px, Py, Pz)
        sys.exit(0)
    except Exception:
        sys.exit(84)

if __name__ == "__main__":
    main()
